---
- hosts: ansi-node1
  become: true
  vars:
    container_count: 1
    default_container_name: nginx
    default_container_image: nginx
#    default_container_command: sleep 1d

  tasks:

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
#      community.docker.docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
#        command: "{{ default_container_command }}"
        state: started
        ports: "8080:80"
      with_sequence: count={{ container_count }}
...
